default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 0000


development:
  <<: *default
  database: blogify_development
  
test:
  <<: *default
  database: blogify_test
  
production:
  <<: *default
  database: blogify_production
  username: blogify
  password: <%= ENV["BLOGIFY_DATABASE_PASSWORD"] %>


